FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o miaosha-server ./cmd/

FROM golang:1.26-alpine
RUN apk --no-cache add ca-certificates tzdata
ENV TZ=Asia/Shanghai
WORKDIR /app
COPY --from=builder /app/miaosha-server .
COPY --from=builder /app/config/config.prod.yaml ./config/config.yaml
EXPOSE 8080 9090
CMD ["./miaosha-server"]
